prefix crm:    <http://www.cidoc-crm.org/cidoc-crm/>
prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?name WHERE {
    ?person rdf:type   crm:E21_Person ;
            rdfs:label ?name ;
}

